name: artifacts
on: push
jobs:
 artifact:
  runs-on: ubuntu-latest
  steps:
   - name: Create a file
     run: | 
      echo "Report Date: $(date)" > report.txt
   - name: Upload the report
     uses: actions/upload-artifact@v4
     with:
      name: build-report
      path: report.txt
      retention-days: 5    
