name: permissions
on: push
permissions:
  contents: read  
jobs:
 secret:
  runs-on: ubuntu-latest
  steps:
   - name: Download the repository
     uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
   - name: List the repositories
     run: ls -la    
